#!/bin/sh

/usr/sbin/udevd --daemon --resolve-names=never
/usr/sbin/udevadm trigger
/usr/sbin/udevadm settle
echo -n "want to drop into shell (y) ? " >/dev/console
read -t 2 KEY
echo >/dev/console
if [ "$KEY" = "Y" -o "$KEY" = "y" ] ; then
  hab sup bash
else
  mount -n -t devtmpfs devtmpfs /dev
  mount -n -t proc     proc     /proc
  mount -n -t sysfs    sysfs    /sys
  mount -n -t tmpfs    tmpfs    /run
  mkdir /dev/pts
  mount -n -t devpts   devpts   /dev/pts
  mount -a
  /usr/bin/busybox udhcpc
  sleep 5
  hab sup load core/openssh
  exec hab sup run
fi

