#!/bin/sh

# /usr/sbin/udevd --daemon --resolve-names=never
# /usr/sbin/udevadm trigger
# /usr/sbin/udevadm settle
mount -n -t devtmpfs devtmpfs /dev
mount -n -t proc     proc     /proc
mount -n -t sysfs    sysfs    /sys
mount -n -t tmpfs    tmpfs    /run
mkdir /dev/pts
mount -n -t devpts   devpts   /dev/pts

# Load modules from /etc/modules
if [ -f /etc/modules ] ; then
	sed 's/\#.*//g' < /etc/modules |
	while read module args; do
		modprobe -q $module $args
	done
fi

# Load dynamic modules required by devices present at boot
find /sys -name modalias | xargs sort -u | xargs /sbin/modprobe -a 2>/dev/null

# Set up module loading for hot-plug devices
echo /usr/bin/mdev > /proc/sys/kernel/hotplug
mdev -s 

hab pkg exec core/busybox-static udhcpc

echo -n "want to drop into shell (y) ? " >/dev/console
read -t 10 KEY
echo >/dev/console
if [ "$KEY" = "Y" -o "$KEY" = "y" ] ; then
  hab sup bash
else
  # TODO: Composite package? 
  hab sup load core/openssh
  hab sup load core/dhclient
  exec hab sup run
fi

